### PR TITLE
Add option to skip cache for static files

### PR DESCRIPTION
**Pull request by esolitos**
As discussed in wodby/drupal-varnish#3 I created this PR to allow skipping caching static files.

### CODE REVIEW

**Comment by csandanov** [comment]
I think we should skip it by default, otherwise, there's a good chance all `64M` of memory storage will be occupied by static files instead of the dynamic content. I believe that's the main issue you had in the first place.

**Comment by esolitos** [comment]
Updated skipping cache for static files by default.

**Comment by csandanov** [comment]
The build is failing for some reason, if you don't have time you can close this PR, I will review and commit these changes.

**Comment by esolitos** [comment]
Sorry, didn't run the builkd, it was a pre-existing typo that passed unnoticed.

**Pull request merged**
